# Form implementation generated from reading ui file 'UI/addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.nameEdit.setObjectName("nameEdit")
        self.verticalLayout.addWidget(self.nameEdit)
        self.roastLevelEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.roastLevelEdit.setObjectName("roastLevelEdit")
        self.verticalLayout.addWidget(self.roastLevelEdit)
        self.typeEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.typeEdit.setObjectName("typeEdit")
        self.verticalLayout.addWidget(self.typeEdit)
        self.tasteEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.tasteEdit.setObjectName("tasteEdit")
        self.verticalLayout.addWidget(self.tasteEdit)
        self.priceEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.priceEdit.setObjectName("priceEdit")
        self.verticalLayout.addWidget(self.priceEdit)
        self.packageSizeEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.packageSizeEdit.setObjectName("packageSizeEdit")
        self.verticalLayout.addWidget(self.packageSizeEdit)
        self.saveButton = QtWidgets.QPushButton(parent=Dialog)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.nameEdit.setPlaceholderText(_translate("Dialog", "Название"))
        self.roastLevelEdit.setPlaceholderText(_translate("Dialog", "Степень обжарки"))
        self.typeEdit.setPlaceholderText(_translate("Dialog", "Тип (молотый/в зернах)"))
        self.tasteEdit.setPlaceholderText(_translate("Dialog", "Описание вкуса"))
        self.priceEdit.setPlaceholderText(_translate("Dialog", "Цена"))
        self.packageSizeEdit.setPlaceholderText(_translate("Dialog", "Объем упаковки"))
        self.saveButton.setText(_translate("Dialog", "Сохранить"))
